name: CI

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build-project:
    name: Build Project
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1

      - name: ccache
        uses: hendrikmuhs/ccache-action@v1.2

      - name: Configure Project
        uses: threeal/cmake-action@v1.3.0

      - name: Formatting code.
        run: bash clang-format-all .

      - name: Build Project
        run: cmake --build build

      - name: Test Project
        run: ctest --test-dir build


